/*
 * generated by Xtext 2.25.0
 */
package com.arsene.dsl.query.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link QueryDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractQueryDslWebModule extends DefaultWebModule {

}
