/*
 * generated by Xtext 2.25.0
 */
package com.arsene.query.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class QueryDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/arsene/query/parser/antlr/internal/InternalQueryDsl.tokens");
	}
}
