####################################################################################################
# Step 1: Build the app
####################################################################################################

FROM rwynn/monstache:6.7.4

# Copying monstache configuration file
COPY monstache.config.toml /app/monstache.config.toml
