/**
 * generated by Xtext 2.25.0
 */
package com.arsene.query.queryDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dsl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.arsene.query.queryDsl.Dsl#getDslVar <em>Dsl Var</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.Dsl#getDslVars <em>Dsl Vars</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.Dsl#getSyntax <em>Syntax</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.Dsl#getTextSearch <em>Text Search</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.Dsl#getFilter <em>Filter</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.Dsl#getField <em>Field</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.Dsl#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see com.arsene.query.queryDsl.QueryDslPackage#getDsl()
 * @model
 * @generated
 */
public interface Dsl extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Dsl Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dsl Var</em>' containment reference.
   * @see #setDslVar(DslVar)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getDsl_DslVar()
   * @model containment="true"
   * @generated
   */
  DslVar getDslVar();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.Dsl#getDslVar <em>Dsl Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dsl Var</em>' containment reference.
   * @see #getDslVar()
   * @generated
   */
  void setDslVar(DslVar value);

  /**
   * Returns the value of the '<em><b>Dsl Vars</b></em>' containment reference list.
   * The list contents are of type {@link com.arsene.query.queryDsl.DslVar}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dsl Vars</em>' containment reference list.
   * @see com.arsene.query.queryDsl.QueryDslPackage#getDsl_DslVars()
   * @model containment="true"
   * @generated
   */
  EList<DslVar> getDslVars();

  /**
   * Returns the value of the '<em><b>Syntax</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Syntax</em>' containment reference.
   * @see #setSyntax(MicroSyntax)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getDsl_Syntax()
   * @model containment="true"
   * @generated
   */
  MicroSyntax getSyntax();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.Dsl#getSyntax <em>Syntax</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Syntax</em>' containment reference.
   * @see #getSyntax()
   * @generated
   */
  void setSyntax(MicroSyntax value);

  /**
   * Returns the value of the '<em><b>Text Search</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text Search</em>' containment reference.
   * @see #setTextSearch(FullTextSearch)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getDsl_TextSearch()
   * @model containment="true"
   * @generated
   */
  FullTextSearch getTextSearch();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.Dsl#getTextSearch <em>Text Search</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text Search</em>' containment reference.
   * @see #getTextSearch()
   * @generated
   */
  void setTextSearch(FullTextSearch value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' containment reference.
   * @see #setFilter(Filter)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getDsl_Filter()
   * @model containment="true"
   * @generated
   */
  Filter getFilter();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.Dsl#getFilter <em>Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' containment reference.
   * @see #getFilter()
   * @generated
   */
  void setFilter(Filter value);

  /**
   * Returns the value of the '<em><b>Field</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' containment reference.
   * @see #setField(DslField)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getDsl_Field()
   * @model containment="true"
   * @generated
   */
  DslField getField();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.Dsl#getField <em>Field</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field</em>' containment reference.
   * @see #getField()
   * @generated
   */
  void setField(DslField value);

  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link com.arsene.query.queryDsl.DslField}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see com.arsene.query.queryDsl.QueryDslPackage#getDsl_Fields()
   * @model containment="true"
   * @generated
   */
  EList<DslField> getFields();

} // Dsl
