/**
 * generated by Xtext 2.25.0
 */
package com.arsene.query.queryDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.arsene.query.queryDsl.FilterExp#getFilterkey <em>Filterkey</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.FilterExp#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see com.arsene.query.queryDsl.QueryDslPackage#getFilterExp()
 * @model
 * @generated
 */
public interface FilterExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Filterkey</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filterkey</em>' containment reference.
   * @see #setFilterkey(FilterKeyword)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getFilterExp_Filterkey()
   * @model containment="true"
   * @generated
   */
  FilterKeyword getFilterkey();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.FilterExp#getFilterkey <em>Filterkey</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filterkey</em>' containment reference.
   * @see #getFilterkey()
   * @generated
   */
  void setFilterkey(FilterKeyword value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getFilterExp_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.FilterExp#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

} // FilterExp
