/**
 * generated by Xtext 2.25.0
 */
package com.arsene.query.queryDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Project Var</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.arsene.query.queryDsl.QueryDslPackage#getProjectVar()
 * @model
 * @generated
 */
public interface ProjectVar extends EObject
{
} // ProjectVar
