/**
 * generated by Xtext 2.25.0
 */
package com.arsene.query.queryDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Quality Metric</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.arsene.query.queryDsl.QualityMetric#getQExp <em>QExp</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.QualityMetric#getOperator <em>Operator</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.QualityMetric#getQExps <em>QExps</em>}</li>
 * </ul>
 *
 * @see com.arsene.query.queryDsl.QueryDslPackage#getQualityMetric()
 * @model
 * @generated
 */
public interface QualityMetric extends EObject
{
  /**
   * Returns the value of the '<em><b>QExp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>QExp</em>' containment reference.
   * @see #setQExp(QExp)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getQualityMetric_QExp()
   * @model containment="true"
   * @generated
   */
  QExp getQExp();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.QualityMetric#getQExp <em>QExp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>QExp</em>' containment reference.
   * @see #getQExp()
   * @generated
   */
  void setQExp(QExp value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' containment reference.
   * @see #setOperator(Operator)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getQualityMetric_Operator()
   * @model containment="true"
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.QualityMetric#getOperator <em>Operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' containment reference.
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

  /**
   * Returns the value of the '<em><b>QExps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>QExps</em>' containment reference.
   * @see #setQExps(QExp)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getQualityMetric_QExps()
   * @model containment="true"
   * @generated
   */
  QExp getQExps();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.QualityMetric#getQExps <em>QExps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>QExps</em>' containment reference.
   * @see #getQExps()
   * @generated
   */
  void setQExps(QExp value);

} // QualityMetric
