/**
 * generated by Xtext 2.25.0
 */
package com.arsene.query.queryDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.arsene.query.queryDsl.QueryDslPackage
 * @generated
 */
public interface QueryDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QueryDslFactory eINSTANCE = com.arsene.query.queryDsl.impl.QueryDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Query Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query Model</em>'.
   * @generated
   */
  QueryModel createQueryModel();

  /**
   * Returns a new object of class '<em>Abstract Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Element</em>'.
   * @generated
   */
  AbstractElement createAbstractElement();

  /**
   * Returns a new object of class '<em>User</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>User</em>'.
   * @generated
   */
  User createUser();

  /**
   * Returns a new object of class '<em>Workspace</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workspace</em>'.
   * @generated
   */
  Workspace createWorkspace();

  /**
   * Returns a new object of class '<em>Project</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Project</em>'.
   * @generated
   */
  Project createProject();

  /**
   * Returns a new object of class '<em>Metamodel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Metamodel</em>'.
   * @generated
   */
  Metamodel createMetamodel();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Dsl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dsl</em>'.
   * @generated
   */
  Dsl createDsl();

  /**
   * Returns a new object of class '<em>Micro Syntax</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Micro Syntax</em>'.
   * @generated
   */
  MicroSyntax createMicroSyntax();

  /**
   * Returns a new object of class '<em>Model Query</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model Query</em>'.
   * @generated
   */
  ModelQuery createModelQuery();

  /**
   * Returns a new object of class '<em>Full Text Search</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Full Text Search</em>'.
   * @generated
   */
  FullTextSearch createFullTextSearch();

  /**
   * Returns a new object of class '<em>Quality Metric</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Quality Metric</em>'.
   * @generated
   */
  QualityMetric createQualityMetric();

  /**
   * Returns a new object of class '<em>Transformable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transformable</em>'.
   * @generated
   */
  Transformable createTransformable();

  /**
   * Returns a new object of class '<em>Trans Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trans Param</em>'.
   * @generated
   */
  TransParam createTransParam();

  /**
   * Returns a new object of class '<em>QExp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>QExp</em>'.
   * @generated
   */
  QExp createQExp();

  /**
   * Returns a new object of class '<em>Qattribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Qattribute</em>'.
   * @generated
   */
  Qattribute createQattribute();

  /**
   * Returns a new object of class '<em>Operator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operator</em>'.
   * @generated
   */
  Operator createOperator();

  /**
   * Returns a new object of class '<em>Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Filter</em>'.
   * @generated
   */
  Filter createFilter();

  /**
   * Returns a new object of class '<em>Filter Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Filter Exp</em>'.
   * @generated
   */
  FilterExp createFilterExp();

  /**
   * Returns a new object of class '<em>Comparison</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comparison</em>'.
   * @generated
   */
  Comparison createComparison();

  /**
   * Returns a new object of class '<em>Filter Keyword</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Filter Keyword</em>'.
   * @generated
   */
  FilterKeyword createFilterKeyword();

  /**
   * Returns a new object of class '<em>Artifact Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Artifact Type</em>'.
   * @generated
   */
  ArtifactType createArtifactType();

  /**
   * Returns a new object of class '<em>User Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>User Var</em>'.
   * @generated
   */
  UserVar createUserVar();

  /**
   * Returns a new object of class '<em>Workspace Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workspace Var</em>'.
   * @generated
   */
  WorkspaceVar createWorkspaceVar();

  /**
   * Returns a new object of class '<em>Project Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Project Var</em>'.
   * @generated
   */
  ProjectVar createProjectVar();

  /**
   * Returns a new object of class '<em>Metamodel Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Metamodel Var</em>'.
   * @generated
   */
  MetamodelVar createMetamodelVar();

  /**
   * Returns a new object of class '<em>Model Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model Var</em>'.
   * @generated
   */
  ModelVar createModelVar();

  /**
   * Returns a new object of class '<em>Dsl Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dsl Var</em>'.
   * @generated
   */
  DslVar createDslVar();

  /**
   * Returns a new object of class '<em>User Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>User Field</em>'.
   * @generated
   */
  UserField createUserField();

  /**
   * Returns a new object of class '<em>Workspace Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workspace Field</em>'.
   * @generated
   */
  WorkspaceField createWorkspaceField();

  /**
   * Returns a new object of class '<em>Project Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Project Field</em>'.
   * @generated
   */
  ProjectField createProjectField();

  /**
   * Returns a new object of class '<em>Metamodel Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Metamodel Field</em>'.
   * @generated
   */
  MetamodelField createMetamodelField();

  /**
   * Returns a new object of class '<em>Model Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model Field</em>'.
   * @generated
   */
  ModelField createModelField();

  /**
   * Returns a new object of class '<em>Dsl Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dsl Field</em>'.
   * @generated
   */
  DslField createDslField();

  /**
   * Returns a new object of class '<em>User Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>User Param</em>'.
   * @generated
   */
  UserParam createUserParam();

  /**
   * Returns a new object of class '<em>Workspace Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workspace Param</em>'.
   * @generated
   */
  WorkspaceParam createWorkspaceParam();

  /**
   * Returns a new object of class '<em>Project Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Project Param</em>'.
   * @generated
   */
  ProjectParam createProjectParam();

  /**
   * Returns a new object of class '<em>Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable</em>'.
   * @generated
   */
  Variable createVariable();

  /**
   * Returns a new object of class '<em>Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expression</em>'.
   * @generated
   */
  Expression createExpression();

  /**
   * Returns a new object of class '<em>Int Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Constant</em>'.
   * @generated
   */
  IntConstant createIntConstant();

  /**
   * Returns a new object of class '<em>String Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Constant</em>'.
   * @generated
   */
  StringConstant createStringConstant();

  /**
   * Returns a new object of class '<em>Bool Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bool Constant</em>'.
   * @generated
   */
  BoolConstant createBoolConstant();

  /**
   * Returns a new object of class '<em>Variable Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable Ref</em>'.
   * @generated
   */
  VariableRef createVariableRef();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  QueryDslPackage getQueryDslPackage();

} //QueryDslFactory
