/**
 * generated by Xtext 2.25.0
 */
package com.arsene.query.queryDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.arsene.query.queryDsl.User#getUservar <em>Uservar</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.User#getUservars <em>Uservars</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.User#getField <em>Field</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.User#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see com.arsene.query.queryDsl.QueryDslPackage#getUser()
 * @model
 * @generated
 */
public interface User extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Uservar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uservar</em>' containment reference.
   * @see #setUservar(UserVar)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getUser_Uservar()
   * @model containment="true"
   * @generated
   */
  UserVar getUservar();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.User#getUservar <em>Uservar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uservar</em>' containment reference.
   * @see #getUservar()
   * @generated
   */
  void setUservar(UserVar value);

  /**
   * Returns the value of the '<em><b>Uservars</b></em>' containment reference list.
   * The list contents are of type {@link com.arsene.query.queryDsl.UserVar}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uservars</em>' containment reference list.
   * @see com.arsene.query.queryDsl.QueryDslPackage#getUser_Uservars()
   * @model containment="true"
   * @generated
   */
  EList<UserVar> getUservars();

  /**
   * Returns the value of the '<em><b>Field</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' containment reference.
   * @see #setField(UserField)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getUser_Field()
   * @model containment="true"
   * @generated
   */
  UserField getField();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.User#getField <em>Field</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field</em>' containment reference.
   * @see #getField()
   * @generated
   */
  void setField(UserField value);

  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link com.arsene.query.queryDsl.UserField}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see com.arsene.query.queryDsl.QueryDslPackage#getUser_Fields()
   * @model containment="true"
   * @generated
   */
  EList<UserField> getFields();

} // User
