/**
 * generated by Xtext 2.25.0
 */
package com.arsene.query.queryDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Workspace</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.arsene.query.queryDsl.Workspace#getSpacevar <em>Spacevar</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.Workspace#getSpacevars <em>Spacevars</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.Workspace#getField <em>Field</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.Workspace#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see com.arsene.query.queryDsl.QueryDslPackage#getWorkspace()
 * @model
 * @generated
 */
public interface Workspace extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Spacevar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spacevar</em>' containment reference.
   * @see #setSpacevar(WorkspaceVar)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getWorkspace_Spacevar()
   * @model containment="true"
   * @generated
   */
  WorkspaceVar getSpacevar();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.Workspace#getSpacevar <em>Spacevar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Spacevar</em>' containment reference.
   * @see #getSpacevar()
   * @generated
   */
  void setSpacevar(WorkspaceVar value);

  /**
   * Returns the value of the '<em><b>Spacevars</b></em>' containment reference list.
   * The list contents are of type {@link com.arsene.query.queryDsl.WorkspaceVar}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spacevars</em>' containment reference list.
   * @see com.arsene.query.queryDsl.QueryDslPackage#getWorkspace_Spacevars()
   * @model containment="true"
   * @generated
   */
  EList<WorkspaceVar> getSpacevars();

  /**
   * Returns the value of the '<em><b>Field</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' containment reference.
   * @see #setField(WorkspaceField)
   * @see com.arsene.query.queryDsl.QueryDslPackage#getWorkspace_Field()
   * @model containment="true"
   * @generated
   */
  WorkspaceField getField();

  /**
   * Sets the value of the '{@link com.arsene.query.queryDsl.Workspace#getField <em>Field</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field</em>' containment reference.
   * @see #getField()
   * @generated
   */
  void setField(WorkspaceField value);

  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link com.arsene.query.queryDsl.WorkspaceField}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see com.arsene.query.queryDsl.QueryDslPackage#getWorkspace_Fields()
   * @model containment="true"
   * @generated
   */
  EList<WorkspaceField> getFields();

} // Workspace
