apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./helm-deployment/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/advanced-query-search-engine: "true"
    io.kompose.service: mongos2
  name: mongos2
spec:
  containers:
    - args:
        - mongos
        - --configdb
        - mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017
        - --port
        - "27017"
        - --bind_ip_all
      image: indamutsa/mongo:$IMAGE_TAG
      name: mongos2
      ports:
        - containerPort: 27017
      resources: {}
  restartPolicy: OnFailure
status: {}
