const UserList = [
  {
    id: 1,
    name: "Nicoli",
    username: "nmackiewicz0",
    nationality: "Norway",
    age: 25,
    country_code: "NO",
    email: "nsellan0@facebook.com",
    phone: "802-491-9365",
    friends: [
      {
        id: 8,
        name: "Killian",
        username: "ksheal7",
        nationality: "Morocco",
        age: 28,
        country_code: "MA",
        email: "krignall7@go.com",
        phone: "712-726-3811",
      },
      {
        id: 9,
        name: "Gisela",
        username: "ggolledge8",
        nationality: "Slovenia",
        age: 56,
        country_code: "SI",
        email: "gmoger8@apache.org",
        phone: "952-898-5657",
      },
      {
        id: 10,
        name: "Misha",
        username: "mgreensted9",
        nationality: "Russia",
        age: 22,
        country_code: "RU",
        email: "mpearn9@engadget.com",
        phone: "132-973-7954",
      },
      {
        id: 11,
        name: "Isidro",
        username: "igaywooda",
        nationality: "Portugal",
        age: 33,
        country_code: "PT",
        email: "istrathmana@usa.gov",
        phone: "925-851-1404",
      },
    ],
  },
  {
    id: 2,
    name: "Garvy",
    username: "gvannini1",
    nationality: "France",
    age: 17,
    country_code: "FR",
    email: "gteasell1@de.vu",
    phone: "120-139-0587",
    friends: [],
  },
  {
    id: 3,
    name: "Tabbitha",
    username: "twisson2",
    nationality: "Portugal",
    age: 12,
    country_code: "PT",
    email: "twilkinson2@a8.net",
    phone: "950-753-1274",
    friends: [
      {
        id: 16,
        name: "Ainsley",
        username: "anaullsf",
        nationality: "Honduras",
        age: 30,
        country_code: "HN",
        email: "ashurlockf@springer.com",
        phone: "368-388-9902",
      },
      {
        id: 17,
        name: "Livy",
        username: "lrenforthg",
        nationality: "Philippines",
        age: 71,
        country_code: "PH",
        email: "lpashbag@cyberchimps.com",
        phone: "314-607-2148",
      },
      {
        id: 18,
        name: "Niki",
        username: "nsimysonh",
        nationality: "Sudan",
        age: 31,
        country_code: "SD",
        email: "nscougallh@telegraph.co.uk",
        phone: "404-648-5683",
      },
    ],
  },
  {
    id: 4,
    name: "Flory",
    username: "fpetraitis3",
    nationality: "Palestinian Territory",
    age: 30,
    country_code: "PS",
    email: "fbolens3@engadget.com",
    phone: "358-789-1224",
    friends: [
      {
        id: 14,
        name: "Sybille",
        username: "smcdunlevyd",
        nationality: "Georgia",
        age: 32,
        country_code: "GE",
        email: "smacmenemyd@scribd.com",
        phone: "509-583-6910",
      },
      {
        id: 15,
        name: "Rennie",
        username: "rtwidalee",
        nationality: "Russia",
        age: 39,
        country_code: "RU",
        email: "rdanieloue@howstuffworks.com",
        phone: "158-511-5037",
      },
      {
        id: 16,
        name: "Ainsley",
        username: "anaullsf",
        nationality: "Honduras",
        age: 30,
        country_code: "HN",
        email: "ashurlockf@springer.com",
        phone: "368-388-9902",
      },
      {
        id: 17,
        name: "Livy",
        username: "lrenforthg",
        nationality: "Philippines",
        age: 71,
        country_code: "PH",
        email: "lpashbag@cyberchimps.com",
        phone: "314-607-2148",
      },
    ],
  },
  {
    id: 5,
    name: "Marleah",
    username: "mpomfrey4",
    nationality: "Poland",
    age: 65,
    country_code: "PL",
    email: "mingreda4@mysql.com",
    phone: "149-345-7927",
    friends: [],
  },
  {
    id: 6,
    name: "Jo-ann",
    username: "jvooght5",
    nationality: "Russia",
    age: 30,
    country_code: "RU",
    email: "jhosten5@spiegel.de",
    phone: "655-123-4725",
    friends: [
      {
        id: 18,
        name: "Niki",
        username: "nsimysonh",
        nationality: "Sudan",
        age: 31,
        country_code: "SD",
        email: "nscougallh@telegraph.co.uk",
        phone: "404-648-5683",
      },
    ],
  },
  {
    id: 7,
    name: "Abbott",
    username: "abulcroft6",
    nationality: "China",
    age: 30,
    country_code: "CN",
    email: "akneaphsey6@hhs.gov",
    phone: "522-933-4463",
    friends: [
      {
        id: 9,
        name: "Gisela",
        username: "ggolledge8",
        nationality: "Slovenia",
        age: 56,
        country_code: "SI",
        email: "gmoger8@apache.org",
        phone: "952-898-5657",
      },
      {
        id: 10,
        name: "Misha",
        username: "mgreensted9",
        nationality: "Russia",
        age: 22,
        country_code: "RU",
        email: "mpearn9@engadget.com",
        phone: "132-973-7954",
      },
    ],
  },
  {
    id: 8,
    name: "Killian",
    username: "ksheal7",
    nationality: "Morocco",
    age: 30,
    country_code: "MA",
    email: "krignall7@go.com",
    phone: "712-726-3811",
    friends: [],
  },
  {
    id: 9,
    name: "Gisela",
    username: "ggolledge8",
    nationality: "Slovenia",
    age: 30,
    country_code: "SI",
    email: "gmoger8@apache.org",
    phone: "952-898-5657",
    friends: [
      {
        id: 5,
        name: "Marleah",
        username: "mpomfrey4",
        nationality: "Poland",
        age: 65,
        country_code: "PL",
        email: "mingreda4@mysql.com",
        phone: "149-345-7927",
      },
      {
        id: 6,
        name: "Jo-ann",
        username: "jvooght5",
        nationality: "Russia",
        age: 30,
        country_code: "RU",
        email: "jhosten5@spiegel.de",
        phone: "655-123-4725",
      },
    ],
  },
  {
    id: 10,
    name: "Misha",
    username: "mgreensted9",
    nationality: "Russia",
    age: 30,
    country_code: "RU",
    email: "mpearn9@engadget.com",
    phone: "132-973-7954",
    friends: [],
  },
  {
    id: 11,
    name: "Isidro",
    username: "igaywooda",
    nationality: "Portugal",
    age: 33,
    country_code: "PT",
    email: "istrathmana@usa.gov",
    phone: "925-851-1404",
    friends: [
      {
        id: 1,
        name: "Nicoli",
        username: "nmackiewicz0",
        nationality: "Norway",
        age: 25,
        country_code: "NO",
        email: "nsellan0@facebook.com",
        phone: "802-491-9365",
      },
      {
        id: 2,
        name: "Garvy",
        username: "gvannini1",
        nationality: "France",
        age: 17,
        country_code: "FR",
        email: "gteasell1@de.vu",
        phone: "120-139-0587",
      },
    ],
  },
  {
    id: 12,
    name: "Debora",
    username: "dcamollib",
    nationality: "Cambodia",
    age: 24,
    country_code: "KH",
    email: "dconeybeareb@uol.com.br",
    phone: "711-549-8730",
    friends: [
      {
        id: 15,
        name: "Rennie",
        username: "rtwidalee",
        nationality: "Russia",
        age: 39,
        country_code: "RU",
        email: "rdanieloue@howstuffworks.com",
        phone: "158-511-5037",
      },
    ],
  },
  {
    id: 13,
    name: "Elise",
    username: "edoegc",
    nationality: "Germany",
    age: 40,
    country_code: "DE",
    email: "edellitc@boston.com",
    phone: "676-975-5649",
    friends: [],
  },
  {
    id: 14,
    name: "Sybille",
    username: "smcdunlevyd",
    nationality: "Georgia",
    age: 32,
    country_code: "GE",
    email: "smacmenemyd@scribd.com",
    phone: "509-583-6910",
    friends: [
      {
        id: 9,
        name: "Gisela",
        username: "ggolledge8",
        nationality: "Slovenia",
        age: 56,
        country_code: "SI",
        email: "gmoger8@apache.org",
        phone: "952-898-5657",
      },
      {
        id: 10,
        name: "Misha",
        username: "mgreensted9",
        nationality: "Russia",
        age: 22,
        country_code: "RU",
        email: "mpearn9@engadget.com",
        phone: "132-973-7954",
      },
    ],
  },
  {
    id: 15,
    name: "Rennie",
    username: "rtwidalee",
    nationality: "Russia",
    age: 39,
    country_code: "RU",
    email: "rdanieloue@howstuffworks.com",
    phone: "158-511-5037",
    friends: [
      {
        id: 8,
        name: "Killian",
        username: "ksheal7",
        nationality: "Morocco",
        age: 28,
        country_code: "MA",
        email: "krignall7@go.com",
        phone: "712-726-3811",
      },
      {
        id: 9,
        name: "Gisela",
        username: "ggolledge8",
        nationality: "Slovenia",
        age: 56,
        country_code: "SI",
        email: "gmoger8@apache.org",
        phone: "952-898-5657",
      },
    ],
  },
  {
    id: 16,
    name: "Ainsley",
    username: "anaullsf",
    nationality: "Honduras",
    age: 30,
    country_code: "HN",
    email: "ashurlockf@springer.com",
    phone: "368-388-9902",
    friends: [
      {
        id: 5,
        name: "Marleah",
        username: "mpomfrey4",
        nationality: "Poland",
        age: 65,
        country_code: "PL",
        email: "mingreda4@mysql.com",
        phone: "149-345-7927",
      },
    ],
  },
  {
    id: 17,
    name: "Livy",
    username: "lrenforthg",
    nationality: "Philippines",
    age: 71,
    country_code: "PH",
    email: "lpashbag@cyberchimps.com",
    phone: "314-607-2148",
    friends: [],
  },
  {
    id: 18,
    name: "Niki",
    username: "nsimysonh",
    nationality: "Sudan",
    age: 31,
    country_code: "SD",
    email: "nscougallh@telegraph.co.uk",
    phone: "404-648-5683",
    friends: [
      {
        id: 2,
        name: "Garvy",
        username: "gvannini1",
        nationality: "France",
        age: 17,
        country_code: "FR",
        email: "gteasell1@de.vu",
        phone: "120-139-0587",
      },
      {
        id: 3,
        name: "Tabbitha",
        username: "twisson2",
        nationality: "Portugal",
        age: 12,
        country_code: "PT",
        email: "twilkinson2@a8.net",
        phone: "950-753-1274",
      },
    ],
  },
  {
    id: 19,
    name: "Dave",
    username: "dgrimsleyi",
    nationality: "Norway",
    age: 26,
    country_code: "NO",
    email: "dtomczynskii@newyorker.com",
    phone: "577-267-6663",
    friends: [
      {
        id: 8,
        name: "Killian",
        username: "ksheal7",
        nationality: "Morocco",
        age: 28,
        country_code: "MA",
        email: "krignall7@go.com",
        phone: "712-726-3811",
      },
      {
        id: 9,
        name: "Gisela",
        username: "ggolledge8",
        nationality: "Slovenia",
        age: 56,
        country_code: "SI",
        email: "gmoger8@apache.org",
        phone: "952-898-5657",
      },
    ],
  },
  {
    id: 20,
    name: "Waite",
    username: "wjorryj",
    nationality: "Russia",
    age: 30,
    country_code: "RU",
    email: "wcharlotj@icio.us",
    phone: "888-428-8433",
    friends: [
      {
        id: 10,
        name: "Misha",
        username: "mgreensted9",
        nationality: "Russia",
        age: 22,
        country_code: "RU",
        email: "mpearn9@engadget.com",
        phone: "132-973-7954",
      },
    ],
  },
];

const MovieList = [
  {
    id: 1,
    name: "Pajama Game, The",
    yearOfPublication: 2012,
    isInTheaters: true,
  },
  {
    id: 2,
    name: "Jonah Who Will Be 25 in the Year 2000 (Jonas qui aura 25 ans en l'an 2000)",
    yearOfPublication: 2018,
    isInTheaters: true,
  },
  {
    id: 3,
    name: "Razorback",
    yearOfPublication: 2006,
    isInTheaters: false,
  },
  {
    id: 4,
    name: "Cinderella Story, A",
    yearOfPublication: 2016,
    isInTheaters: false,
  },
  {
    id: 5,
    name: "Beverly Hills Chihuahua",
    yearOfPublication: 2018,
    isInTheaters: false,
  },
  {
    id: 6,
    name: "Man Who Loved Cat Dancing, The",
    yearOfPublication: 2002,
    isInTheaters: true,
  },
  {
    id: 7,
    name: "Shy People",
    yearOfPublication: 2020,
    isInTheaters: false,
  },
  {
    id: 8,
    name: "Ice Station Zebra",
    yearOfPublication: 2019,
    isInTheaters: false,
  },
  {
    id: 9,
    name: "Jeopardy (a.k.a. A Woman in Jeopardy)",
    yearOfPublication: 2020,
    isInTheaters: true,
  },
  {
    id: 10,
    name: "Square, The",
    yearOfPublication: 2003,
    isInTheaters: false,
  },
  {
    id: 11,
    name: "Family Band: The Cowsills Story ",
    yearOfPublication: 2012,
    isInTheaters: true,
  },
  {
    id: 12,
    name: "Wild Angels, The",
    yearOfPublication: 2014,
    isInTheaters: true,
  },
  {
    id: 13,
    name: "Castle Keep",
    yearOfPublication: 2000,
    isInTheaters: false,
  },
  {
    id: 14,
    name: "Night of Dark Shadows",
    yearOfPublication: 2018,
    isInTheaters: true,
  },
  {
    id: 15,
    name: "Along the Ridge (Anche libero va bene)",
    yearOfPublication: 2008,
    isInTheaters: true,
  },
  {
    id: 16,
    name: "Joanna",
    yearOfPublication: 2006,
    isInTheaters: true,
  },
  {
    id: 17,
    name: "Violette (Violette Nozière)",
    yearOfPublication: 2002,
    isInTheaters: true,
  },
  {
    id: 18,
    name: "Haunted Echoes",
    yearOfPublication: 2005,
    isInTheaters: false,
  },
  {
    id: 19,
    name: "Ghosts of Cité Soleil",
    yearOfPublication: 2009,
    isInTheaters: false,
  },
  {
    id: 20,
    name: "Come Back to Me",
    yearOfPublication: 2017,
    isInTheaters: true,
  },
];

module.exports = { UserList, MovieList };
