# In this cluster of microservices, we define elastastic as engine and its logging and visualization supporting tools (logstash, kibana and filebeat)
# In the second part, we synchronize our search engine with the persistence api

# The next thing is to define a crawler that go through files asynchronsously and extracts keywords and index it as well (save it db)
# Then build the complete search api 

version: "3.4"

services:
  # Mongo cluster  -- Sharded cluster
  #################################################
  adminmongo:
    container_name: adminmongo
    image: indamutsa/adminmongo
    ports:
      - 9990:1234
    environment:
      - HOST=0.0.0.0
    networks:
      - search-engine

  # Shard 1
  mongors1n1:
    container_name: mongors1n1
    image: mongo:4.2
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 27018:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - ./mongo-bundle/sharded/mongo_cluster/data1:/data/db
    networks:
      - search-engine

  mongors1n2:
    container_name: mongors1n2
    image: mongo:4.2
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 27027:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - ./mongo-bundle/sharded/mongo_cluster/data2:/data/db
    networks:
      - search-engine

  mongors1n3:
    container_name: mongors1n3
    image: mongo:4.2
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 27037:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - ./mongo-bundle/sharded/mongo_cluster/data3:/data/db
    networks:
      - search-engine

  # Shard 2
  mongors2n1:
    container_name: mongors2n1
    image: mongo:4.2
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 27047:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - ./mongo-bundle/sharded/mongo_cluster/data4:/data/db
    networks:
      - search-engine

  mongors2n2:
    container_name: mongors2n2
    image: mongo:4.2
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 27057:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - ./mongo-bundle/sharded/mongo_cluster/data5:/data/db
    networks:
      - search-engine

  mongors2n3:
    container_name: mongors2n3
    image: mongo:4.2
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 27067:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - ./mongo-bundle/sharded/mongo_cluster/data6:/data/db
    networks:
      - search-engine

  # Configuration server
  mongocfg1:
    container_name: mongocfg1
    image: mongo:4.2
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017 --bind_ip_all
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - ./mongo-bundle/sharded/mongo_cluster/config1:/data/db
    networks:
      - search-engine

  mongocfg2:
    container_name: mongocfg2
    image: mongo:4.2
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017 --bind_ip_all
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - ./mongo-bundle/sharded/mongo_cluster/config2:/data/db
    networks:
      - search-engine

  mongocfg3:
    container_name: mongocfg3
    image: mongo:4.2
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017 --bind_ip_all
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - ./mongo-bundle/sharded/mongo_cluster/config3:/data/db
    networks:
      - search-engine

  # The router
  mongos1:
    container_name: mongos1
    image: mongo:4.2
    depends_on:
      - mongocfg1
      - mongocfg2
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all
    ports:
      - 27019:27017
    expose:
      - "27017"
    volumes:
      - ./setup/addShards.js:/home/app/addShards.js
    networks:
      - search-engine

  mongos2:
    container_name: mongos2
    image: mongo:4.2
    depends_on:
      - mongocfg1
      - mongocfg2
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all
    ports:
      - 27020:27017
    expose:
      - "27017"
    networks:
      - search-engine

  # A shortlived container for starting the cluster
  setup-rs:
    container_name: setup-rs
    build: ./setup
    depends_on:
      - "mongos1"
    networks:
      - search-engine

# Defining the network
######################################################
networks:
  search-engine:
    external: false

volumes:
  elasticsearch:
