apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./helm-deployment/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/advanced-query-search-engine: "true"
    io.kompose.service: mongocfg3
  name: mongocfg3
spec:
  containers:
    - args:
        - mongod
        - --configsvr
        - --replSet
        - mongors1conf
        - --dbpath
        - /data/db
        - --port
        - "27017"
        - --bind_ip_all
      env:
        - name: TERM
          value: xterm
      image: indamutsa/mongo:$IMAGE_TAG
      name: mongocfg3
      ports:
        - containerPort: 27017
      resources: {}
      volumeMounts:
        - mountPath: /data/db
          name: mongocfg3-claim0
  restartPolicy: OnFailure
  volumes:
    - name: mongocfg3-claim0
      persistentVolumeClaim:
        claimName: mongocfg3-claim0
status: {}
