/*
 * generated by Xtext 2.25.0
 */
package com.arsene.query.ide.contentassist.antlr;

import com.arsene.query.ide.contentassist.antlr.internal.InternalQueryDslParser;
import com.arsene.query.services.QueryDslGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class QueryDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(QueryDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, QueryDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAbstractElementAccess().getAlternatives(), "rule__AbstractElement__Alternatives");
			builder.put(grammarAccess.getMetamodelAccess().getAlternatives_6_1(), "rule__Metamodel__Alternatives_6_1");
			builder.put(grammarAccess.getModelAccess().getAlternatives_6_1(), "rule__Model__Alternatives_6_1");
			builder.put(grammarAccess.getDslAccess().getAlternatives_6_1(), "rule__Dsl__Alternatives_6_1");
			builder.put(grammarAccess.getQueryLangAccess().getAlternatives(), "rule__QueryLang__Alternatives");
			builder.put(grammarAccess.getFullTextSearchAccess().getAlternatives_4(), "rule__FullTextSearch__Alternatives_4");
			builder.put(grammarAccess.getTransParamAccess().getTypeAlternatives_0(), "rule__TransParam__TypeAlternatives_0");
			builder.put(grammarAccess.getQattributeAccess().getTypeAlternatives_0(), "rule__Qattribute__TypeAlternatives_0");
			builder.put(grammarAccess.getOperatorAccess().getOpAlternatives_0(), "rule__Operator__OpAlternatives_0");
			builder.put(grammarAccess.getComparisonAccess().getTypeAlternatives_0(), "rule__Comparison__TypeAlternatives_0");
			builder.put(grammarAccess.getFilterKeywordAccess().getTypeAlternatives_0(), "rule__FilterKeyword__TypeAlternatives_0");
			builder.put(grammarAccess.getArtifactTypeAccess().getTypeNameAlternatives_0(), "rule__ArtifactType__TypeNameAlternatives_0");
			builder.put(grammarAccess.getUserFieldAccess().getTypeNameAlternatives_0(), "rule__UserField__TypeNameAlternatives_0");
			builder.put(grammarAccess.getWorkspaceFieldAccess().getTypeNameAlternatives_0(), "rule__WorkspaceField__TypeNameAlternatives_0");
			builder.put(grammarAccess.getProjectFieldAccess().getTypeNameAlternatives_0(), "rule__ProjectField__TypeNameAlternatives_0");
			builder.put(grammarAccess.getMetamodelFieldAccess().getTypeNameAlternatives_0(), "rule__MetamodelField__TypeNameAlternatives_0");
			builder.put(grammarAccess.getModelFieldAccess().getTypeNameAlternatives_0(), "rule__ModelField__TypeNameAlternatives_0");
			builder.put(grammarAccess.getDslFieldAccess().getTypeNameAlternatives_0(), "rule__DslField__TypeNameAlternatives_0");
			builder.put(grammarAccess.getUserParamAccess().getTypeNameAlternatives_0(), "rule__UserParam__TypeNameAlternatives_0");
			builder.put(grammarAccess.getWorkspaceParamAccess().getTypeNameAlternatives_0(), "rule__WorkspaceParam__TypeNameAlternatives_0");
			builder.put(grammarAccess.getProjectParamAccess().getTypeNameAlternatives_0(), "rule__ProjectParam__TypeNameAlternatives_0");
			builder.put(grammarAccess.getMetamodelParamAccess().getAlternatives(), "rule__MetamodelParam__Alternatives");
			builder.put(grammarAccess.getMetaParamAccess().getAlternatives(), "rule__MetaParam__Alternatives");
			builder.put(grammarAccess.getParamAccess().getAlternatives(), "rule__Param__Alternatives");
			builder.put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
			builder.put(grammarAccess.getExpressionAccess().getValueAlternatives_2_1_0(), "rule__Expression__ValueAlternatives_2_1_0");
			builder.put(grammarAccess.getUserAccess().getGroup(), "rule__User__Group__0");
			builder.put(grammarAccess.getUserAccess().getGroup_4(), "rule__User__Group_4__0");
			builder.put(grammarAccess.getUserAccess().getGroup_9(), "rule__User__Group_9__0");
			builder.put(grammarAccess.getWorkspaceAccess().getGroup(), "rule__Workspace__Group__0");
			builder.put(grammarAccess.getWorkspaceAccess().getGroup_4(), "rule__Workspace__Group_4__0");
			builder.put(grammarAccess.getWorkspaceAccess().getGroup_9(), "rule__Workspace__Group_9__0");
			builder.put(grammarAccess.getProjectAccess().getGroup(), "rule__Project__Group__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_4(), "rule__Project__Group_4__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_9(), "rule__Project__Group_9__0");
			builder.put(grammarAccess.getMetamodelAccess().getGroup(), "rule__Metamodel__Group__0");
			builder.put(grammarAccess.getMetamodelAccess().getGroup_4(), "rule__Metamodel__Group_4__0");
			builder.put(grammarAccess.getMetamodelAccess().getGroup_6(), "rule__Metamodel__Group_6__0");
			builder.put(grammarAccess.getMetamodelAccess().getGroup_10(), "rule__Metamodel__Group_10__0");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup_4(), "rule__Model__Group_4__0");
			builder.put(grammarAccess.getModelAccess().getGroup_6(), "rule__Model__Group_6__0");
			builder.put(grammarAccess.getModelAccess().getGroup_10(), "rule__Model__Group_10__0");
			builder.put(grammarAccess.getDslAccess().getGroup(), "rule__Dsl__Group__0");
			builder.put(grammarAccess.getDslAccess().getGroup_4(), "rule__Dsl__Group_4__0");
			builder.put(grammarAccess.getDslAccess().getGroup_6(), "rule__Dsl__Group_6__0");
			builder.put(grammarAccess.getDslAccess().getGroup_10(), "rule__Dsl__Group_10__0");
			builder.put(grammarAccess.getMicroSyntaxAccess().getGroup(), "rule__MicroSyntax__Group__0");
			builder.put(grammarAccess.getModelQueryAccess().getGroup(), "rule__ModelQuery__Group__0");
			builder.put(grammarAccess.getFullTextSearchAccess().getGroup(), "rule__FullTextSearch__Group__0");
			builder.put(grammarAccess.getFullTextSearchAccess().getGroup_3(), "rule__FullTextSearch__Group_3__0");
			builder.put(grammarAccess.getFullTextSearchAccess().getGroup_4_0(), "rule__FullTextSearch__Group_4_0__0");
			builder.put(grammarAccess.getFullTextSearchAccess().getGroup_4_1(), "rule__FullTextSearch__Group_4_1__0");
			builder.put(grammarAccess.getQualityMetricAccess().getGroup(), "rule__QualityMetric__Group__0");
			builder.put(grammarAccess.getQualityMetricAccess().getGroup_3(), "rule__QualityMetric__Group_3__0");
			builder.put(grammarAccess.getTransformableAccess().getGroup(), "rule__Transformable__Group__0");
			builder.put(grammarAccess.getTransformableAccess().getGroup_2(), "rule__Transformable__Group_2__0");
			builder.put(grammarAccess.getTransformableAccess().getGroup_3(), "rule__Transformable__Group_3__0");
			builder.put(grammarAccess.getQExpAccess().getGroup(), "rule__QExp__Group__0");
			builder.put(grammarAccess.getFilterAccess().getGroup(), "rule__Filter__Group__0");
			builder.put(grammarAccess.getFilterAccess().getGroup_3(), "rule__Filter__Group_3__0");
			builder.put(grammarAccess.getFilterAccess().getGroup_4(), "rule__Filter__Group_4__0");
			builder.put(grammarAccess.getFilterExpAccess().getGroup(), "rule__FilterExp__Group__0");
			builder.put(grammarAccess.getUserVarAccess().getGroup(), "rule__UserVar__Group__0");
			builder.put(grammarAccess.getWorkspaceVarAccess().getGroup(), "rule__WorkspaceVar__Group__0");
			builder.put(grammarAccess.getProjectVarAccess().getGroup(), "rule__ProjectVar__Group__0");
			builder.put(grammarAccess.getMetamodelVarAccess().getGroup(), "rule__MetamodelVar__Group__0");
			builder.put(grammarAccess.getModelVarAccess().getGroup(), "rule__ModelVar__Group__0");
			builder.put(grammarAccess.getDslVarAccess().getGroup(), "rule__DslVar__Group__0");
			builder.put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
			builder.put(grammarAccess.getExpressionAccess().getGroup_0(), "rule__Expression__Group_0__0");
			builder.put(grammarAccess.getExpressionAccess().getGroup_1(), "rule__Expression__Group_1__0");
			builder.put(grammarAccess.getExpressionAccess().getGroup_2(), "rule__Expression__Group_2__0");
			builder.put(grammarAccess.getExpressionAccess().getGroup_3(), "rule__Expression__Group_3__0");
			builder.put(grammarAccess.getQueryModelAccess().getElementsAssignment(), "rule__QueryModel__ElementsAssignment");
			builder.put(grammarAccess.getUserAccess().getUservarAssignment_3(), "rule__User__UservarAssignment_3");
			builder.put(grammarAccess.getUserAccess().getUservarsAssignment_4_1(), "rule__User__UservarsAssignment_4_1");
			builder.put(grammarAccess.getUserAccess().getFieldAssignment_8(), "rule__User__FieldAssignment_8");
			builder.put(grammarAccess.getUserAccess().getFieldsAssignment_9_1(), "rule__User__FieldsAssignment_9_1");
			builder.put(grammarAccess.getWorkspaceAccess().getSpacevarAssignment_3(), "rule__Workspace__SpacevarAssignment_3");
			builder.put(grammarAccess.getWorkspaceAccess().getSpacevarsAssignment_4_1(), "rule__Workspace__SpacevarsAssignment_4_1");
			builder.put(grammarAccess.getWorkspaceAccess().getFieldAssignment_8(), "rule__Workspace__FieldAssignment_8");
			builder.put(grammarAccess.getWorkspaceAccess().getFieldsAssignment_9_1(), "rule__Workspace__FieldsAssignment_9_1");
			builder.put(grammarAccess.getProjectAccess().getProjectvarAssignment_3(), "rule__Project__ProjectvarAssignment_3");
			builder.put(grammarAccess.getProjectAccess().getProjectvarsAssignment_4_1(), "rule__Project__ProjectvarsAssignment_4_1");
			builder.put(grammarAccess.getProjectAccess().getFieldAssignment_8(), "rule__Project__FieldAssignment_8");
			builder.put(grammarAccess.getProjectAccess().getFieldsAssignment_9_1(), "rule__Project__FieldsAssignment_9_1");
			builder.put(grammarAccess.getMetamodelAccess().getMetamodelVarAssignment_3(), "rule__Metamodel__MetamodelVarAssignment_3");
			builder.put(grammarAccess.getMetamodelAccess().getMetamodelVarsAssignment_4_1(), "rule__Metamodel__MetamodelVarsAssignment_4_1");
			builder.put(grammarAccess.getMetamodelAccess().getSyntaxAssignment_6_1_0(), "rule__Metamodel__SyntaxAssignment_6_1_0");
			builder.put(grammarAccess.getMetamodelAccess().getTextSearchAssignment_6_1_1(), "rule__Metamodel__TextSearchAssignment_6_1_1");
			builder.put(grammarAccess.getMetamodelAccess().getFilterAssignment_6_1_2(), "rule__Metamodel__FilterAssignment_6_1_2");
			builder.put(grammarAccess.getMetamodelAccess().getQmAssignment_6_1_3(), "rule__Metamodel__QmAssignment_6_1_3");
			builder.put(grammarAccess.getMetamodelAccess().getTransfoAssignment_6_1_4(), "rule__Metamodel__TransfoAssignment_6_1_4");
			builder.put(grammarAccess.getMetamodelAccess().getFieldAssignment_9(), "rule__Metamodel__FieldAssignment_9");
			builder.put(grammarAccess.getMetamodelAccess().getFieldsAssignment_10_1(), "rule__Metamodel__FieldsAssignment_10_1");
			builder.put(grammarAccess.getModelAccess().getModelVarAssignment_3(), "rule__Model__ModelVarAssignment_3");
			builder.put(grammarAccess.getModelAccess().getModelVarsAssignment_4_1(), "rule__Model__ModelVarsAssignment_4_1");
			builder.put(grammarAccess.getModelAccess().getSyntaxAssignment_6_1_0(), "rule__Model__SyntaxAssignment_6_1_0");
			builder.put(grammarAccess.getModelAccess().getTextSearchAssignment_6_1_1(), "rule__Model__TextSearchAssignment_6_1_1");
			builder.put(grammarAccess.getModelAccess().getFilterAssignment_6_1_2(), "rule__Model__FilterAssignment_6_1_2");
			builder.put(grammarAccess.getModelAccess().getQAssignment_6_1_3(), "rule__Model__QAssignment_6_1_3");
			builder.put(grammarAccess.getModelAccess().getFieldAssignment_9(), "rule__Model__FieldAssignment_9");
			builder.put(grammarAccess.getModelAccess().getFieldsAssignment_10_1(), "rule__Model__FieldsAssignment_10_1");
			builder.put(grammarAccess.getDslAccess().getDslVarAssignment_3(), "rule__Dsl__DslVarAssignment_3");
			builder.put(grammarAccess.getDslAccess().getDslVarsAssignment_4_1(), "rule__Dsl__DslVarsAssignment_4_1");
			builder.put(grammarAccess.getDslAccess().getSyntaxAssignment_6_1_0(), "rule__Dsl__SyntaxAssignment_6_1_0");
			builder.put(grammarAccess.getDslAccess().getTextSearchAssignment_6_1_1(), "rule__Dsl__TextSearchAssignment_6_1_1");
			builder.put(grammarAccess.getDslAccess().getFilterAssignment_6_1_2(), "rule__Dsl__FilterAssignment_6_1_2");
			builder.put(grammarAccess.getDslAccess().getFieldAssignment_9(), "rule__Dsl__FieldAssignment_9");
			builder.put(grammarAccess.getDslAccess().getFieldsAssignment_10_1(), "rule__Dsl__FieldsAssignment_10_1");
			builder.put(grammarAccess.getMicroSyntaxAccess().getExpAssignment_2(), "rule__MicroSyntax__ExpAssignment_2");
			builder.put(grammarAccess.getModelQueryAccess().getExprAssignment_6(), "rule__ModelQuery__ExprAssignment_6");
			builder.put(grammarAccess.getFullTextSearchAccess().getExpAssignment_2(), "rule__FullTextSearch__ExpAssignment_2");
			builder.put(grammarAccess.getFullTextSearchAccess().getExpsAssignment_3_1(), "rule__FullTextSearch__ExpsAssignment_3_1");
			builder.put(grammarAccess.getFullTextSearchAccess().getOpAssignment_4_1_3(), "rule__FullTextSearch__OpAssignment_4_1_3");
			builder.put(grammarAccess.getQualityMetricAccess().getQExpAssignment_2(), "rule__QualityMetric__QExpAssignment_2");
			builder.put(grammarAccess.getQualityMetricAccess().getOperatorAssignment_3_0(), "rule__QualityMetric__OperatorAssignment_3_0");
			builder.put(grammarAccess.getQualityMetricAccess().getQExpsAssignment_3_1(), "rule__QualityMetric__QExpsAssignment_3_1");
			builder.put(grammarAccess.getTransformableAccess().getParamAssignment_2_0(), "rule__Transformable__ParamAssignment_2_0");
			builder.put(grammarAccess.getTransformableAccess().getExpAssignment_2_2(), "rule__Transformable__ExpAssignment_2_2");
			builder.put(grammarAccess.getTransformableAccess().getParamAssignment_3_1(), "rule__Transformable__ParamAssignment_3_1");
			builder.put(grammarAccess.getTransformableAccess().getExpAssignment_3_3(), "rule__Transformable__ExpAssignment_3_3");
			builder.put(grammarAccess.getTransParamAccess().getTypeAssignment(), "rule__TransParam__TypeAssignment");
			builder.put(grammarAccess.getQExpAccess().getQAttrAssignment_0(), "rule__QExp__QAttrAssignment_0");
			builder.put(grammarAccess.getQExpAccess().getCompAssignment_1(), "rule__QExp__CompAssignment_1");
			builder.put(grammarAccess.getQExpAccess().getNAssignment_2(), "rule__QExp__NAssignment_2");
			builder.put(grammarAccess.getQattributeAccess().getTypeAssignment(), "rule__Qattribute__TypeAssignment");
			builder.put(grammarAccess.getOperatorAccess().getOpAssignment(), "rule__Operator__OpAssignment");
			builder.put(grammarAccess.getFilterAccess().getFilterExpAssignment_2(), "rule__Filter__FilterExpAssignment_2");
			builder.put(grammarAccess.getFilterAccess().getFilterExpsAssignment_3_1(), "rule__Filter__FilterExpsAssignment_3_1");
			builder.put(grammarAccess.getFilterAccess().getCompAssignment_4_3(), "rule__Filter__CompAssignment_4_3");
			builder.put(grammarAccess.getFilterAccess().getExpAssignment_4_4(), "rule__Filter__ExpAssignment_4_4");
			builder.put(grammarAccess.getFilterExpAccess().getFilterkeyAssignment_0(), "rule__FilterExp__FilterkeyAssignment_0");
			builder.put(grammarAccess.getFilterExpAccess().getExpAssignment_2(), "rule__FilterExp__ExpAssignment_2");
			builder.put(grammarAccess.getComparisonAccess().getTypeAssignment(), "rule__Comparison__TypeAssignment");
			builder.put(grammarAccess.getFilterKeywordAccess().getTypeAssignment(), "rule__FilterKeyword__TypeAssignment");
			builder.put(grammarAccess.getArtifactTypeAccess().getTypeNameAssignment(), "rule__ArtifactType__TypeNameAssignment");
			builder.put(grammarAccess.getUserVarAccess().getExpAssignment_2(), "rule__UserVar__ExpAssignment_2");
			builder.put(grammarAccess.getWorkspaceVarAccess().getExpAssignment_2(), "rule__WorkspaceVar__ExpAssignment_2");
			builder.put(grammarAccess.getProjectVarAccess().getExpAssignment_2(), "rule__ProjectVar__ExpAssignment_2");
			builder.put(grammarAccess.getMetamodelVarAccess().getExpAssignment_2(), "rule__MetamodelVar__ExpAssignment_2");
			builder.put(grammarAccess.getModelVarAccess().getExpAssignment_2(), "rule__ModelVar__ExpAssignment_2");
			builder.put(grammarAccess.getDslVarAccess().getExpAssignment_2(), "rule__DslVar__ExpAssignment_2");
			builder.put(grammarAccess.getUserFieldAccess().getTypeNameAssignment(), "rule__UserField__TypeNameAssignment");
			builder.put(grammarAccess.getWorkspaceFieldAccess().getTypeNameAssignment(), "rule__WorkspaceField__TypeNameAssignment");
			builder.put(grammarAccess.getProjectFieldAccess().getTypeNameAssignment(), "rule__ProjectField__TypeNameAssignment");
			builder.put(grammarAccess.getMetamodelFieldAccess().getTypeNameAssignment(), "rule__MetamodelField__TypeNameAssignment");
			builder.put(grammarAccess.getModelFieldAccess().getTypeNameAssignment(), "rule__ModelField__TypeNameAssignment");
			builder.put(grammarAccess.getDslFieldAccess().getTypeNameAssignment(), "rule__DslField__TypeNameAssignment");
			builder.put(grammarAccess.getUserParamAccess().getTypeNameAssignment(), "rule__UserParam__TypeNameAssignment");
			builder.put(grammarAccess.getWorkspaceParamAccess().getTypeNameAssignment(), "rule__WorkspaceParam__TypeNameAssignment");
			builder.put(grammarAccess.getProjectParamAccess().getTypeNameAssignment(), "rule__ProjectParam__TypeNameAssignment");
			builder.put(grammarAccess.getVariableAccess().getNameAssignment_1(), "rule__Variable__NameAssignment_1");
			builder.put(grammarAccess.getVariableAccess().getExpressionAssignment_3(), "rule__Variable__ExpressionAssignment_3");
			builder.put(grammarAccess.getExpressionAccess().getValueAssignment_0_1(), "rule__Expression__ValueAssignment_0_1");
			builder.put(grammarAccess.getExpressionAccess().getValueAssignment_1_1(), "rule__Expression__ValueAssignment_1_1");
			builder.put(grammarAccess.getExpressionAccess().getValueAssignment_2_1(), "rule__Expression__ValueAssignment_2_1");
			builder.put(grammarAccess.getExpressionAccess().getVariableAssignment_3_1(), "rule__Expression__VariableAssignment_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private QueryDslGrammarAccess grammarAccess;

	@Override
	protected InternalQueryDslParser createParser() {
		InternalQueryDslParser result = new InternalQueryDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public QueryDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QueryDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
