/*
 * generated by Xtext 2.25.0
 */
package com.arsene.dsl.query;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QueryDslRuntimeModule extends AbstractQueryDslRuntimeModule {
}
