<!--?xml version="1.0" encoding="UTF-8"?--> <html> <head></head> <body> <ecore:epackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bz391624" nsuri="http://www.eclipse.org/emf/texo/test/model/issues/bz391624" nsprefix="bz391624"> <eclassifiers xsi:type="ecore:EClass" name="Book" esupertypes="../samples/identifiable.ecore#//Identifiable"> <estructuralfeatures xsi:type="ecore:EReference" name="authors" upperBound="-1" eType="#//Author" containment="true" /> </eclassifiers> <eclassifiers xsi:type="ecore:EClass" name="Author" esupertypes="../samples/identifiable.ecore#//NotIdentifiable"> <estructuralfeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" /> </eclassifiers> </ecore:epackage> </body> </html> 