<!--?xml version="1.0" encoding="UTF-8"?--> <html> <head></head> <body> <ecore:epackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="samples" nsuri="http:///name/njbartlett/osgi/emf/samples.ecore" nsprefix="name.njbartlett.osgi.emf.samples"> <eclassifiers xsi:type="ecore:EClass" name="Author"> <estructuralfeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" /> <estructuralfeatures xsi:type="ecore:EReference" name="books" upperBound="-1" eType="#//Book" /> </eclassifiers> <eclassifiers xsi:type="ecore:EClass" name="Book"> <estructuralfeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" /> <estructuralfeatures xsi:type="ecore:EReference" name="author" eType="#//Author" /> </eclassifiers> </ecore:epackage> </body> </html> 