apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./helm-deployment/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: setup-rs
  name: setup-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: setup-rs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./helm-deployment/
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/advanced-query-search-engine: "true"
        io.kompose.service: setup-rs
    spec:
      containers:
        - image: indamutsa/setup:$IMAGE_TAG
          name: setup-rs
          resources: {}
      restartPolicy: Always
status: {}
