/*
 * generated by Xtext 2.25.0
 */
package com.arsene.dsl.query.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class QueryDslUiModule extends AbstractQueryDslUiModule {

	public QueryDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
