apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -c --out helm-chart
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/kubernetes-search-engine: "true"
    io.kompose.service: adminmongo
  name: adminmongo
spec:
  containers:
    - env:
        - name: HOST
          value: 0.0.0.0
      image: indamutsa/adminmongo
      name: adminmongo
      ports:
        - containerPort: 1234
      resources: {}
  restartPolicy: OnFailure
status: {}
