apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c --out helm-chart
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-search
  name: frontend-search
spec:
  ports:
    - name: "3500"
      port: 3500
      targetPort: 3500
  selector:
    io.kompose.service: frontend-search
status:
  loadBalancer: {}
