apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -c --out helm-chart
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/kubernetes-search-engine: "true"
    io.kompose.service: kibana
  name: kibana
spec:
  containers:
    - image: indamutsa/kibana:v1.0
      name: kibana
      ports:
        - containerPort: 5601
      resources: {}
  restartPolicy: OnFailure
status: {}
