apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -c --out helm-chart
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/kubernetes-search-engine: "true"
    io.kompose.service: logstash
  name: logstash
spec:
  containers:
    - image: indamutsa/logstash:v1.0
      name: logstash
      ports:
        - containerPort: 5044
        - containerPort: 5000
        - containerPort: 5000
          protocol: UDP
        - containerPort: 9600
      resources: {}
  restartPolicy: OnFailure
status: {}
