apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c --out helm-chart
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: metrics-calculator
  name: metrics-calculator
spec:
  ports:
    - name: "8186"
      port: 8186
      targetPort: 8186
  selector:
    io.kompose.service: metrics-calculator
status:
  loadBalancer: {}
