apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -c --out helm-chart
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/kubernetes-search-engine: "true"
    io.kompose.service: model-transformation
  name: model-transformation
spec:
  containers:
    - env:
        - name: HOST
          value: 0.0.0.0
      image: indamutsa/etl-transformation:v1.3
      name: etl-transformation
      ports:
        - containerPort: 8085
      resources: {}
  restartPolicy: OnFailure
status: {}
