apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -c --out helm-chart
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/kubernetes-search-engine: "true"
    io.kompose.service: mongos1
  name: mongos1
spec:
  containers:
    - args:
        - mongos
        - --configdb
        - mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017
        - --port
        - "27017"
        - --bind_ip_all
      image: mongo:4.2
      name: mongos1
      ports:
        - containerPort: 27017
      resources: {}
      volumeMounts:
        - mountPath: /home/app/addShards.js
          name: mongos1-claim0
  restartPolicy: OnFailure
  volumes:
    - name: mongos1-claim0
      persistentVolumeClaim:
        claimName: mongos1-claim0
status: {}
