apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -c --out helm-chart
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/kubernetes-search-engine: "true"
    io.kompose.service: mongors2n1
  name: mongors2n1
spec:
  containers:
    - args:
        - mongod
        - --shardsvr
        - --replSet
        - mongors2
        - --dbpath
        - /data/db
        - --port
        - "27017"
        - --bind_ip_all
      env:
        - name: TERM
          value: xterm
      image: mongo:4.2
      name: mongors2n1
      ports:
        - containerPort: 27017
      resources: {}
      volumeMounts:
        - mountPath: /data/db
          name: mongors2n1-claim0
  restartPolicy: OnFailure
  volumes:
    - name: mongors2n1-claim0
      persistentVolumeClaim:
        claimName: mongors2n1-claim0
status: {}
