apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c --out helm-chart
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: persistence-api
  name: persistence-api
spec:
  ports:
    - name: "3200"
      port: 3200
      targetPort: 3200
  selector:
    io.kompose.service: persistence-api
status:
  loadBalancer: {}
