/**
 * generated by Xtext 2.25.0
 */
package com.arsene.query.queryDsl.impl;

import com.arsene.query.queryDsl.Dsl;
import com.arsene.query.queryDsl.DslField;
import com.arsene.query.queryDsl.DslVar;
import com.arsene.query.queryDsl.Filter;
import com.arsene.query.queryDsl.FullTextSearch;
import com.arsene.query.queryDsl.MicroSyntax;
import com.arsene.query.queryDsl.QueryDslPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dsl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.arsene.query.queryDsl.impl.DslImpl#getDslVar <em>Dsl Var</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.DslImpl#getDslVars <em>Dsl Vars</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.DslImpl#getSyntax <em>Syntax</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.DslImpl#getTextSearch <em>Text Search</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.DslImpl#getFilter <em>Filter</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.DslImpl#getField <em>Field</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.DslImpl#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DslImpl extends AbstractElementImpl implements Dsl
{
  /**
   * The cached value of the '{@link #getDslVar() <em>Dsl Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDslVar()
   * @generated
   * @ordered
   */
  protected DslVar dslVar;

  /**
   * The cached value of the '{@link #getDslVars() <em>Dsl Vars</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDslVars()
   * @generated
   * @ordered
   */
  protected EList<DslVar> dslVars;

  /**
   * The cached value of the '{@link #getSyntax() <em>Syntax</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSyntax()
   * @generated
   * @ordered
   */
  protected MicroSyntax syntax;

  /**
   * The cached value of the '{@link #getTextSearch() <em>Text Search</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTextSearch()
   * @generated
   * @ordered
   */
  protected FullTextSearch textSearch;

  /**
   * The cached value of the '{@link #getFilter() <em>Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFilter()
   * @generated
   * @ordered
   */
  protected Filter filter;

  /**
   * The cached value of the '{@link #getField() <em>Field</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getField()
   * @generated
   * @ordered
   */
  protected DslField field;

  /**
   * The cached value of the '{@link #getFields() <em>Fields</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFields()
   * @generated
   * @ordered
   */
  protected EList<DslField> fields;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DslImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryDslPackage.Literals.DSL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DslVar getDslVar()
  {
    return dslVar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDslVar(DslVar newDslVar, NotificationChain msgs)
  {
    DslVar oldDslVar = dslVar;
    dslVar = newDslVar;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QueryDslPackage.DSL__DSL_VAR, oldDslVar, newDslVar);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDslVar(DslVar newDslVar)
  {
    if (newDslVar != dslVar)
    {
      NotificationChain msgs = null;
      if (dslVar != null)
        msgs = ((InternalEObject)dslVar).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.DSL__DSL_VAR, null, msgs);
      if (newDslVar != null)
        msgs = ((InternalEObject)newDslVar).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.DSL__DSL_VAR, null, msgs);
      msgs = basicSetDslVar(newDslVar, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.DSL__DSL_VAR, newDslVar, newDslVar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DslVar> getDslVars()
  {
    if (dslVars == null)
    {
      dslVars = new EObjectContainmentEList<DslVar>(DslVar.class, this, QueryDslPackage.DSL__DSL_VARS);
    }
    return dslVars;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MicroSyntax getSyntax()
  {
    return syntax;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSyntax(MicroSyntax newSyntax, NotificationChain msgs)
  {
    MicroSyntax oldSyntax = syntax;
    syntax = newSyntax;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QueryDslPackage.DSL__SYNTAX, oldSyntax, newSyntax);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSyntax(MicroSyntax newSyntax)
  {
    if (newSyntax != syntax)
    {
      NotificationChain msgs = null;
      if (syntax != null)
        msgs = ((InternalEObject)syntax).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.DSL__SYNTAX, null, msgs);
      if (newSyntax != null)
        msgs = ((InternalEObject)newSyntax).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.DSL__SYNTAX, null, msgs);
      msgs = basicSetSyntax(newSyntax, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.DSL__SYNTAX, newSyntax, newSyntax));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FullTextSearch getTextSearch()
  {
    return textSearch;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTextSearch(FullTextSearch newTextSearch, NotificationChain msgs)
  {
    FullTextSearch oldTextSearch = textSearch;
    textSearch = newTextSearch;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QueryDslPackage.DSL__TEXT_SEARCH, oldTextSearch, newTextSearch);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTextSearch(FullTextSearch newTextSearch)
  {
    if (newTextSearch != textSearch)
    {
      NotificationChain msgs = null;
      if (textSearch != null)
        msgs = ((InternalEObject)textSearch).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.DSL__TEXT_SEARCH, null, msgs);
      if (newTextSearch != null)
        msgs = ((InternalEObject)newTextSearch).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.DSL__TEXT_SEARCH, null, msgs);
      msgs = basicSetTextSearch(newTextSearch, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.DSL__TEXT_SEARCH, newTextSearch, newTextSearch));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Filter getFilter()
  {
    return filter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFilter(Filter newFilter, NotificationChain msgs)
  {
    Filter oldFilter = filter;
    filter = newFilter;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QueryDslPackage.DSL__FILTER, oldFilter, newFilter);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFilter(Filter newFilter)
  {
    if (newFilter != filter)
    {
      NotificationChain msgs = null;
      if (filter != null)
        msgs = ((InternalEObject)filter).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.DSL__FILTER, null, msgs);
      if (newFilter != null)
        msgs = ((InternalEObject)newFilter).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.DSL__FILTER, null, msgs);
      msgs = basicSetFilter(newFilter, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.DSL__FILTER, newFilter, newFilter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DslField getField()
  {
    return field;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetField(DslField newField, NotificationChain msgs)
  {
    DslField oldField = field;
    field = newField;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QueryDslPackage.DSL__FIELD, oldField, newField);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setField(DslField newField)
  {
    if (newField != field)
    {
      NotificationChain msgs = null;
      if (field != null)
        msgs = ((InternalEObject)field).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.DSL__FIELD, null, msgs);
      if (newField != null)
        msgs = ((InternalEObject)newField).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.DSL__FIELD, null, msgs);
      msgs = basicSetField(newField, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.DSL__FIELD, newField, newField));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DslField> getFields()
  {
    if (fields == null)
    {
      fields = new EObjectContainmentEList<DslField>(DslField.class, this, QueryDslPackage.DSL__FIELDS);
    }
    return fields;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QueryDslPackage.DSL__DSL_VAR:
        return basicSetDslVar(null, msgs);
      case QueryDslPackage.DSL__DSL_VARS:
        return ((InternalEList<?>)getDslVars()).basicRemove(otherEnd, msgs);
      case QueryDslPackage.DSL__SYNTAX:
        return basicSetSyntax(null, msgs);
      case QueryDslPackage.DSL__TEXT_SEARCH:
        return basicSetTextSearch(null, msgs);
      case QueryDslPackage.DSL__FILTER:
        return basicSetFilter(null, msgs);
      case QueryDslPackage.DSL__FIELD:
        return basicSetField(null, msgs);
      case QueryDslPackage.DSL__FIELDS:
        return ((InternalEList<?>)getFields()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QueryDslPackage.DSL__DSL_VAR:
        return getDslVar();
      case QueryDslPackage.DSL__DSL_VARS:
        return getDslVars();
      case QueryDslPackage.DSL__SYNTAX:
        return getSyntax();
      case QueryDslPackage.DSL__TEXT_SEARCH:
        return getTextSearch();
      case QueryDslPackage.DSL__FILTER:
        return getFilter();
      case QueryDslPackage.DSL__FIELD:
        return getField();
      case QueryDslPackage.DSL__FIELDS:
        return getFields();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QueryDslPackage.DSL__DSL_VAR:
        setDslVar((DslVar)newValue);
        return;
      case QueryDslPackage.DSL__DSL_VARS:
        getDslVars().clear();
        getDslVars().addAll((Collection<? extends DslVar>)newValue);
        return;
      case QueryDslPackage.DSL__SYNTAX:
        setSyntax((MicroSyntax)newValue);
        return;
      case QueryDslPackage.DSL__TEXT_SEARCH:
        setTextSearch((FullTextSearch)newValue);
        return;
      case QueryDslPackage.DSL__FILTER:
        setFilter((Filter)newValue);
        return;
      case QueryDslPackage.DSL__FIELD:
        setField((DslField)newValue);
        return;
      case QueryDslPackage.DSL__FIELDS:
        getFields().clear();
        getFields().addAll((Collection<? extends DslField>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.DSL__DSL_VAR:
        setDslVar((DslVar)null);
        return;
      case QueryDslPackage.DSL__DSL_VARS:
        getDslVars().clear();
        return;
      case QueryDslPackage.DSL__SYNTAX:
        setSyntax((MicroSyntax)null);
        return;
      case QueryDslPackage.DSL__TEXT_SEARCH:
        setTextSearch((FullTextSearch)null);
        return;
      case QueryDslPackage.DSL__FILTER:
        setFilter((Filter)null);
        return;
      case QueryDslPackage.DSL__FIELD:
        setField((DslField)null);
        return;
      case QueryDslPackage.DSL__FIELDS:
        getFields().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.DSL__DSL_VAR:
        return dslVar != null;
      case QueryDslPackage.DSL__DSL_VARS:
        return dslVars != null && !dslVars.isEmpty();
      case QueryDslPackage.DSL__SYNTAX:
        return syntax != null;
      case QueryDslPackage.DSL__TEXT_SEARCH:
        return textSearch != null;
      case QueryDslPackage.DSL__FILTER:
        return filter != null;
      case QueryDslPackage.DSL__FIELD:
        return field != null;
      case QueryDslPackage.DSL__FIELDS:
        return fields != null && !fields.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //DslImpl
