/**
 * generated by Xtext 2.25.0
 */
package com.arsene.query.queryDsl.impl;

import com.arsene.query.queryDsl.Project;
import com.arsene.query.queryDsl.ProjectField;
import com.arsene.query.queryDsl.ProjectVar;
import com.arsene.query.queryDsl.QueryDslPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Project</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.arsene.query.queryDsl.impl.ProjectImpl#getProjectvar <em>Projectvar</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.ProjectImpl#getProjectvars <em>Projectvars</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.ProjectImpl#getField <em>Field</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.ProjectImpl#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProjectImpl extends AbstractElementImpl implements Project
{
  /**
   * The cached value of the '{@link #getProjectvar() <em>Projectvar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProjectvar()
   * @generated
   * @ordered
   */
  protected ProjectVar projectvar;

  /**
   * The cached value of the '{@link #getProjectvars() <em>Projectvars</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProjectvars()
   * @generated
   * @ordered
   */
  protected EList<ProjectVar> projectvars;

  /**
   * The cached value of the '{@link #getField() <em>Field</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getField()
   * @generated
   * @ordered
   */
  protected ProjectField field;

  /**
   * The cached value of the '{@link #getFields() <em>Fields</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFields()
   * @generated
   * @ordered
   */
  protected EList<ProjectField> fields;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProjectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryDslPackage.Literals.PROJECT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProjectVar getProjectvar()
  {
    return projectvar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetProjectvar(ProjectVar newProjectvar, NotificationChain msgs)
  {
    ProjectVar oldProjectvar = projectvar;
    projectvar = newProjectvar;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QueryDslPackage.PROJECT__PROJECTVAR, oldProjectvar, newProjectvar);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProjectvar(ProjectVar newProjectvar)
  {
    if (newProjectvar != projectvar)
    {
      NotificationChain msgs = null;
      if (projectvar != null)
        msgs = ((InternalEObject)projectvar).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.PROJECT__PROJECTVAR, null, msgs);
      if (newProjectvar != null)
        msgs = ((InternalEObject)newProjectvar).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.PROJECT__PROJECTVAR, null, msgs);
      msgs = basicSetProjectvar(newProjectvar, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.PROJECT__PROJECTVAR, newProjectvar, newProjectvar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ProjectVar> getProjectvars()
  {
    if (projectvars == null)
    {
      projectvars = new EObjectContainmentEList<ProjectVar>(ProjectVar.class, this, QueryDslPackage.PROJECT__PROJECTVARS);
    }
    return projectvars;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProjectField getField()
  {
    return field;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetField(ProjectField newField, NotificationChain msgs)
  {
    ProjectField oldField = field;
    field = newField;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QueryDslPackage.PROJECT__FIELD, oldField, newField);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setField(ProjectField newField)
  {
    if (newField != field)
    {
      NotificationChain msgs = null;
      if (field != null)
        msgs = ((InternalEObject)field).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.PROJECT__FIELD, null, msgs);
      if (newField != null)
        msgs = ((InternalEObject)newField).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.PROJECT__FIELD, null, msgs);
      msgs = basicSetField(newField, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.PROJECT__FIELD, newField, newField));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ProjectField> getFields()
  {
    if (fields == null)
    {
      fields = new EObjectContainmentEList<ProjectField>(ProjectField.class, this, QueryDslPackage.PROJECT__FIELDS);
    }
    return fields;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QueryDslPackage.PROJECT__PROJECTVAR:
        return basicSetProjectvar(null, msgs);
      case QueryDslPackage.PROJECT__PROJECTVARS:
        return ((InternalEList<?>)getProjectvars()).basicRemove(otherEnd, msgs);
      case QueryDslPackage.PROJECT__FIELD:
        return basicSetField(null, msgs);
      case QueryDslPackage.PROJECT__FIELDS:
        return ((InternalEList<?>)getFields()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QueryDslPackage.PROJECT__PROJECTVAR:
        return getProjectvar();
      case QueryDslPackage.PROJECT__PROJECTVARS:
        return getProjectvars();
      case QueryDslPackage.PROJECT__FIELD:
        return getField();
      case QueryDslPackage.PROJECT__FIELDS:
        return getFields();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QueryDslPackage.PROJECT__PROJECTVAR:
        setProjectvar((ProjectVar)newValue);
        return;
      case QueryDslPackage.PROJECT__PROJECTVARS:
        getProjectvars().clear();
        getProjectvars().addAll((Collection<? extends ProjectVar>)newValue);
        return;
      case QueryDslPackage.PROJECT__FIELD:
        setField((ProjectField)newValue);
        return;
      case QueryDslPackage.PROJECT__FIELDS:
        getFields().clear();
        getFields().addAll((Collection<? extends ProjectField>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.PROJECT__PROJECTVAR:
        setProjectvar((ProjectVar)null);
        return;
      case QueryDslPackage.PROJECT__PROJECTVARS:
        getProjectvars().clear();
        return;
      case QueryDslPackage.PROJECT__FIELD:
        setField((ProjectField)null);
        return;
      case QueryDslPackage.PROJECT__FIELDS:
        getFields().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.PROJECT__PROJECTVAR:
        return projectvar != null;
      case QueryDslPackage.PROJECT__PROJECTVARS:
        return projectvars != null && !projectvars.isEmpty();
      case QueryDslPackage.PROJECT__FIELD:
        return field != null;
      case QueryDslPackage.PROJECT__FIELDS:
        return fields != null && !fields.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ProjectImpl
