/**
 * generated by Xtext 2.25.0
 */
package com.arsene.query.queryDsl.impl;

import com.arsene.query.queryDsl.QueryDslPackage;
import com.arsene.query.queryDsl.User;
import com.arsene.query.queryDsl.UserField;
import com.arsene.query.queryDsl.UserVar;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>User</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.arsene.query.queryDsl.impl.UserImpl#getUservar <em>Uservar</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.UserImpl#getUservars <em>Uservars</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.UserImpl#getField <em>Field</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.UserImpl#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UserImpl extends AbstractElementImpl implements User
{
  /**
   * The cached value of the '{@link #getUservar() <em>Uservar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUservar()
   * @generated
   * @ordered
   */
  protected UserVar uservar;

  /**
   * The cached value of the '{@link #getUservars() <em>Uservars</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUservars()
   * @generated
   * @ordered
   */
  protected EList<UserVar> uservars;

  /**
   * The cached value of the '{@link #getField() <em>Field</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getField()
   * @generated
   * @ordered
   */
  protected UserField field;

  /**
   * The cached value of the '{@link #getFields() <em>Fields</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFields()
   * @generated
   * @ordered
   */
  protected EList<UserField> fields;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UserImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryDslPackage.Literals.USER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UserVar getUservar()
  {
    return uservar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUservar(UserVar newUservar, NotificationChain msgs)
  {
    UserVar oldUservar = uservar;
    uservar = newUservar;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QueryDslPackage.USER__USERVAR, oldUservar, newUservar);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUservar(UserVar newUservar)
  {
    if (newUservar != uservar)
    {
      NotificationChain msgs = null;
      if (uservar != null)
        msgs = ((InternalEObject)uservar).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.USER__USERVAR, null, msgs);
      if (newUservar != null)
        msgs = ((InternalEObject)newUservar).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.USER__USERVAR, null, msgs);
      msgs = basicSetUservar(newUservar, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.USER__USERVAR, newUservar, newUservar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<UserVar> getUservars()
  {
    if (uservars == null)
    {
      uservars = new EObjectContainmentEList<UserVar>(UserVar.class, this, QueryDslPackage.USER__USERVARS);
    }
    return uservars;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UserField getField()
  {
    return field;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetField(UserField newField, NotificationChain msgs)
  {
    UserField oldField = field;
    field = newField;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QueryDslPackage.USER__FIELD, oldField, newField);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setField(UserField newField)
  {
    if (newField != field)
    {
      NotificationChain msgs = null;
      if (field != null)
        msgs = ((InternalEObject)field).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.USER__FIELD, null, msgs);
      if (newField != null)
        msgs = ((InternalEObject)newField).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.USER__FIELD, null, msgs);
      msgs = basicSetField(newField, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.USER__FIELD, newField, newField));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<UserField> getFields()
  {
    if (fields == null)
    {
      fields = new EObjectContainmentEList<UserField>(UserField.class, this, QueryDslPackage.USER__FIELDS);
    }
    return fields;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QueryDslPackage.USER__USERVAR:
        return basicSetUservar(null, msgs);
      case QueryDslPackage.USER__USERVARS:
        return ((InternalEList<?>)getUservars()).basicRemove(otherEnd, msgs);
      case QueryDslPackage.USER__FIELD:
        return basicSetField(null, msgs);
      case QueryDslPackage.USER__FIELDS:
        return ((InternalEList<?>)getFields()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QueryDslPackage.USER__USERVAR:
        return getUservar();
      case QueryDslPackage.USER__USERVARS:
        return getUservars();
      case QueryDslPackage.USER__FIELD:
        return getField();
      case QueryDslPackage.USER__FIELDS:
        return getFields();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QueryDslPackage.USER__USERVAR:
        setUservar((UserVar)newValue);
        return;
      case QueryDslPackage.USER__USERVARS:
        getUservars().clear();
        getUservars().addAll((Collection<? extends UserVar>)newValue);
        return;
      case QueryDslPackage.USER__FIELD:
        setField((UserField)newValue);
        return;
      case QueryDslPackage.USER__FIELDS:
        getFields().clear();
        getFields().addAll((Collection<? extends UserField>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.USER__USERVAR:
        setUservar((UserVar)null);
        return;
      case QueryDslPackage.USER__USERVARS:
        getUservars().clear();
        return;
      case QueryDslPackage.USER__FIELD:
        setField((UserField)null);
        return;
      case QueryDslPackage.USER__FIELDS:
        getFields().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.USER__USERVAR:
        return uservar != null;
      case QueryDslPackage.USER__USERVARS:
        return uservars != null && !uservars.isEmpty();
      case QueryDslPackage.USER__FIELD:
        return field != null;
      case QueryDslPackage.USER__FIELDS:
        return fields != null && !fields.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //UserImpl
