/**
 * generated by Xtext 2.25.0
 */
package com.arsene.query.queryDsl.impl;

import com.arsene.query.queryDsl.QueryDslPackage;
import com.arsene.query.queryDsl.Workspace;
import com.arsene.query.queryDsl.WorkspaceField;
import com.arsene.query.queryDsl.WorkspaceVar;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Workspace</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.arsene.query.queryDsl.impl.WorkspaceImpl#getSpacevar <em>Spacevar</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.WorkspaceImpl#getSpacevars <em>Spacevars</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.WorkspaceImpl#getField <em>Field</em>}</li>
 *   <li>{@link com.arsene.query.queryDsl.impl.WorkspaceImpl#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WorkspaceImpl extends AbstractElementImpl implements Workspace
{
  /**
   * The cached value of the '{@link #getSpacevar() <em>Spacevar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpacevar()
   * @generated
   * @ordered
   */
  protected WorkspaceVar spacevar;

  /**
   * The cached value of the '{@link #getSpacevars() <em>Spacevars</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpacevars()
   * @generated
   * @ordered
   */
  protected EList<WorkspaceVar> spacevars;

  /**
   * The cached value of the '{@link #getField() <em>Field</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getField()
   * @generated
   * @ordered
   */
  protected WorkspaceField field;

  /**
   * The cached value of the '{@link #getFields() <em>Fields</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFields()
   * @generated
   * @ordered
   */
  protected EList<WorkspaceField> fields;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WorkspaceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryDslPackage.Literals.WORKSPACE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkspaceVar getSpacevar()
  {
    return spacevar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSpacevar(WorkspaceVar newSpacevar, NotificationChain msgs)
  {
    WorkspaceVar oldSpacevar = spacevar;
    spacevar = newSpacevar;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QueryDslPackage.WORKSPACE__SPACEVAR, oldSpacevar, newSpacevar);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpacevar(WorkspaceVar newSpacevar)
  {
    if (newSpacevar != spacevar)
    {
      NotificationChain msgs = null;
      if (spacevar != null)
        msgs = ((InternalEObject)spacevar).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.WORKSPACE__SPACEVAR, null, msgs);
      if (newSpacevar != null)
        msgs = ((InternalEObject)newSpacevar).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.WORKSPACE__SPACEVAR, null, msgs);
      msgs = basicSetSpacevar(newSpacevar, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.WORKSPACE__SPACEVAR, newSpacevar, newSpacevar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WorkspaceVar> getSpacevars()
  {
    if (spacevars == null)
    {
      spacevars = new EObjectContainmentEList<WorkspaceVar>(WorkspaceVar.class, this, QueryDslPackage.WORKSPACE__SPACEVARS);
    }
    return spacevars;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkspaceField getField()
  {
    return field;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetField(WorkspaceField newField, NotificationChain msgs)
  {
    WorkspaceField oldField = field;
    field = newField;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QueryDslPackage.WORKSPACE__FIELD, oldField, newField);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setField(WorkspaceField newField)
  {
    if (newField != field)
    {
      NotificationChain msgs = null;
      if (field != null)
        msgs = ((InternalEObject)field).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.WORKSPACE__FIELD, null, msgs);
      if (newField != null)
        msgs = ((InternalEObject)newField).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QueryDslPackage.WORKSPACE__FIELD, null, msgs);
      msgs = basicSetField(newField, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.WORKSPACE__FIELD, newField, newField));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WorkspaceField> getFields()
  {
    if (fields == null)
    {
      fields = new EObjectContainmentEList<WorkspaceField>(WorkspaceField.class, this, QueryDslPackage.WORKSPACE__FIELDS);
    }
    return fields;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QueryDslPackage.WORKSPACE__SPACEVAR:
        return basicSetSpacevar(null, msgs);
      case QueryDslPackage.WORKSPACE__SPACEVARS:
        return ((InternalEList<?>)getSpacevars()).basicRemove(otherEnd, msgs);
      case QueryDslPackage.WORKSPACE__FIELD:
        return basicSetField(null, msgs);
      case QueryDslPackage.WORKSPACE__FIELDS:
        return ((InternalEList<?>)getFields()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QueryDslPackage.WORKSPACE__SPACEVAR:
        return getSpacevar();
      case QueryDslPackage.WORKSPACE__SPACEVARS:
        return getSpacevars();
      case QueryDslPackage.WORKSPACE__FIELD:
        return getField();
      case QueryDslPackage.WORKSPACE__FIELDS:
        return getFields();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QueryDslPackage.WORKSPACE__SPACEVAR:
        setSpacevar((WorkspaceVar)newValue);
        return;
      case QueryDslPackage.WORKSPACE__SPACEVARS:
        getSpacevars().clear();
        getSpacevars().addAll((Collection<? extends WorkspaceVar>)newValue);
        return;
      case QueryDslPackage.WORKSPACE__FIELD:
        setField((WorkspaceField)newValue);
        return;
      case QueryDslPackage.WORKSPACE__FIELDS:
        getFields().clear();
        getFields().addAll((Collection<? extends WorkspaceField>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.WORKSPACE__SPACEVAR:
        setSpacevar((WorkspaceVar)null);
        return;
      case QueryDslPackage.WORKSPACE__SPACEVARS:
        getSpacevars().clear();
        return;
      case QueryDslPackage.WORKSPACE__FIELD:
        setField((WorkspaceField)null);
        return;
      case QueryDslPackage.WORKSPACE__FIELDS:
        getFields().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.WORKSPACE__SPACEVAR:
        return spacevar != null;
      case QueryDslPackage.WORKSPACE__SPACEVARS:
        return spacevars != null && !spacevars.isEmpty();
      case QueryDslPackage.WORKSPACE__FIELD:
        return field != null;
      case QueryDslPackage.WORKSPACE__FIELDS:
        return fields != null && !fields.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //WorkspaceImpl
