apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mdeforge
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/indamutsa/advanced-query.git
    targetRevision: HEAD
    path: cluster-helm-deployment
    helm:
      valueFiles:
        - values.yaml
      version: v2  # Replace with your desired Helm chart version
      values: |
        # Additional Helm values if needed.
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
