# prettier-ignore

{{- range .Values.mongodb.shards }}
{{- range .nodes }}

# Service for {{ . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ . }}
  labels:
    app: {{ . }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: {{ . }}
---

# StatefulSet for {{ . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ . }}
spec:
  serviceName: {{ . }}
  replicas: {{ $.Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ . }}
  template:
    metadata:
      labels:
        app: {{ . }}
    spec:
      containers:
      - name: {{ . }}
        image: {{ $.Values.mongodb.image }}
        command:
        - mongod
        - --shardsvr
        - --replSet
        - {{ $.name }}
        - --dbpath
        - /data/db
        - --port
        - "27017"
        - --bind_ip_all
        ports:
        - containerPort: 27017
        env:
        - name: TERM
          value: xterm
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ $.Values.mongodb.storageSize }}
---
{{- end }}
{{- end }}
