/**
 * generated by Xtext 2.25.0
 */
package com.arsene.dsl.query.queryDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Global Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.arsene.dsl.query.queryDsl.QueryDslPackage#getGlobalCommand()
 * @model
 * @generated
 */
public interface GlobalCommand extends Instruction
{
} // GlobalCommand
