/**
 * generated by Xtext 2.25.0
 */
package com.arsene.dsl.query.queryDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.arsene.dsl.query.queryDsl.PrintCommand#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see com.arsene.dsl.query.queryDsl.QueryDslPackage#getPrintCommand()
 * @model
 * @generated
 */
public interface PrintCommand extends GlobalCommand
{
  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link com.arsene.dsl.query.queryDsl.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see com.arsene.dsl.query.queryDsl.QueryDslPackage#getPrintCommand_Params()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getParams();

} // PrintCommand
