/**
 * generated by Xtext 2.25.0
 */
package com.arsene.dsl.query.queryDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.arsene.dsl.query.queryDsl.VariableDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link com.arsene.dsl.query.queryDsl.VariableDeclaration#getInitExp <em>Init Exp</em>}</li>
 * </ul>
 *
 * @see com.arsene.dsl.query.queryDsl.QueryDslPackage#getVariableDeclaration()
 * @model
 * @generated
 */
public interface VariableDeclaration extends Instruction
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.arsene.dsl.query.queryDsl.QueryDslPackage#getVariableDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.arsene.dsl.query.queryDsl.VariableDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Init Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init Exp</em>' containment reference.
   * @see #setInitExp(Expression)
   * @see com.arsene.dsl.query.queryDsl.QueryDslPackage#getVariableDeclaration_InitExp()
   * @model containment="true"
   * @generated
   */
  Expression getInitExp();

  /**
   * Sets the value of the '{@link com.arsene.dsl.query.queryDsl.VariableDeclaration#getInitExp <em>Init Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init Exp</em>' containment reference.
   * @see #getInitExp()
   * @generated
   */
  void setInitExp(Expression value);

} // VariableDeclaration
