apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/search-engine: "true"
        io.kompose.service: elasticsearch
    spec:
      containers:
      - env:
        - name: ELASTIC_PASSWORD
          value: changeme
        - name: ES_JAVA_OPTS
          value: -Xmx256m -Xms256m
        - name: discovery.type
          value: single-node
        image: indamutsa/elasticsearch:v1.0
        imagePullPolicy: ""
        name: elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elastic-bundle/elasticsearch/config/elasticsearch.yml
          name: elasticsearch-claim0
          readOnly: true
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: elasticsearch-claim0
        persistentVolumeClaim:
          claimName: elasticsearch-claim0
          readOnly: true
      - name: elasticsearch
        persistentVolumeClaim:
          claimName: elasticsearch
status: {}
