apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: filebeat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/search-engine: "true"
        io.kompose.service: filebeat
    spec:
      containers:
      - args:
        - filebeat
        - -e
        - --strict.perms=false
        image: indamutsa/filebeat:v1.0
        imagePullPolicy: ""
        name: filebeat
        resources: {}
        volumeMounts:
        - mountPath: /logs
          name: filebeat-claim0
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-claim1
          readOnly: true
        - mountPath: /usr/share/filebeat/dockerlogs
          name: filebeat-claim2
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: filebeat-claim3
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: filebeat-claim0
        persistentVolumeClaim:
          claimName: filebeat-claim0
      - name: filebeat-claim1
        persistentVolumeClaim:
          claimName: filebeat-claim1
          readOnly: true
      - name: filebeat-claim2
        persistentVolumeClaim:
          claimName: filebeat-claim2
          readOnly: true
      - name: filebeat-claim3
        persistentVolumeClaim:
          claimName: filebeat-claim3
status: {}
