apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-search
  name: frontend-search
spec:
  ports:
  - name: "3500"
    port: 3500
    targetPort: 3500
  selector:
    io.kompose.service: frontend-search
status:
  loadBalancer: {}
