apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/search-engine: "true"
        io.kompose.service: logstash
    spec:
      containers:
      - env:
        - name: LS_JAVA_OPTS
          value: -Xmx256m -Xms256m
        image: indamutsa/logstash:v1.0
        imagePullPolicy: ""
        name: logstash
        ports:
        - containerPort: 5044
        - containerPort: 5000
        - containerPort: 5000
          protocol: UDP
        - containerPort: 9600
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/logstash/config/logstash.yml
          name: logstash-claim0
          readOnly: true
        - mountPath: /usr/share/logstash/pipeline
          name: logstash-claim1
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: logstash-claim0
        persistentVolumeClaim:
          claimName: logstash-claim0
          readOnly: true
      - name: logstash-claim1
        persistentVolumeClaim:
          claimName: logstash-claim1
          readOnly: true
status: {}
