apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongos1
  name: mongos1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongos1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/search-engine: "true"
        io.kompose.service: mongos1
    spec:
      containers:
      - args:
        - mongos
        - --configdb
        - mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017
        - --port
        - "27017"
        - --bind_ip_all
        image: mongo:4.2
        imagePullPolicy: ""
        name: mongos1
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /home/app/addShards.js
          name: mongos1-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mongos1-claim0
        persistentVolumeClaim:
          claimName: mongos1-claim0
status: {}
