apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongors2n3
  name: mongors2n3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongors2n3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/search-engine: "true"
        io.kompose.service: mongors2n3
    spec:
      containers:
      - args:
        - mongod
        - --shardsvr
        - --replSet
        - mongors2
        - --dbpath
        - /data/db
        - --port
        - "27017"
        - --bind_ip_all
        env:
        - name: TERM
          value: xterm
        image: mongo:4.2
        imagePullPolicy: ""
        name: mongors2n3
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongors2n3-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mongors2n3-claim0
        persistentVolumeClaim:
          claimName: mongors2n3-claim0
status: {}
