apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: persistence-api
  name: persistence-api
spec:
  ports:
  - name: "3200"
    port: 3200
    targetPort: 3200
  selector:
    io.kompose.service: persistence-api
status:
  loadBalancer: {}
