apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: query-engine
  name: query-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: query-engine
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/search-engine: "true"
        io.kompose.service: query-engine
    spec:
      containers:
      - image: query-engine
        imagePullPolicy: ""
        name: query-engine
        ports:
        - containerPort: 3300
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: query-engine-claim0
        - mountPath: /app/node_modules
          name: query-engine-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: query-engine-claim0
        persistentVolumeClaim:
          claimName: query-engine-claim0
      - name: query-engine-claim1
        persistentVolumeClaim:
          claimName: query-engine-claim1
status: {}
