apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: setup-rs
  name: setup-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: setup-rs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/search-engine: "true"
        io.kompose.service: setup-rs
    spec:
      containers:
      - image: setup-rs
        imagePullPolicy: ""
        name: setup-rs
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
