# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontendSearch.name }}
spec:
  replicas: {{ .Values.frontendSearch.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontendSearch.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontendSearch.label }}
    spec:
      containers:
      - name: {{ .Values.frontendSearch.containerName }}
        image: {{ .Values.frontendSearch.image }}
        ports:
        - containerPort: {{ .Values.frontendSearch.containerPort }}
        # resources:
        #   requests:
        #     memory: {{ .Values.frontendSearch.resources.requests.memory }}
        #     cpu: {{ .Values.frontendSearch.resources.requests.cpu | quote}}
        #   limits:
        #     memory: {{ .Values.frontendSearch.resources.limits.memory }}
        #     cpu: {{ .Values.frontendSearch.resources.limits.cpu | quote }}
---
# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendSearch.name }}
spec:
  selector:
    app: {{ .Values.frontendSearch.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontendSearch.servicePort }}
      targetPort: {{ .Values.frontendSearch.containerPort }}
  type: {{ .Values.frontendSearch.serviceType }}

