/*
 * generated by Xtext 2.25.0
 */
package com.arsene.query.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQueryDslScopeProvider extends DelegatingScopeProvider {
}
