apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./helm-deployment/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: query-engine
  name: query-engine
spec:
  ports:
    - name: "3300"
      port: 3300
      targetPort: 3300
  selector:
    io.kompose.service: query-engine
status:
  loadBalancer: {}
