apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./helm-deployment/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: mongos1
  name: mongos1
spec:
  ports:
    - name: "27019"
      port: 27019
      targetPort: 27017
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongos1
status:
  loadBalancer: {}
